/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package javamongo;

import java.util.Scanner;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;

public class App {
    public static void main(String[] args) {
        String uri = "mongodb://localhost:27017/";
        Scanner scanner = new Scanner(System.in);

        try {
            MongoClient mongoClient = MongoClients.create(uri);
            MongoDatabase treeDB = mongoClient.getDatabase("VancouverOpenData_Trees");

            System.out.println("Do you want to re-import the data? (yes/no)");
            String reimportData = scanner.next();
            String fieldsColl = "TreeFields";

            if (reimportData.toLowerCase().equals("yes")) {
                System.out.println("Do you want to update the map? (yes/no)");
                String updateMap = scanner.next();
                Boolean update = (updateMap.toLowerCase().equals("yes")) ? true : false;
                Etl etl = new Etl(treeDB, update);
                etl.rebuildTreeFields("Trees", fieldsColl);
            }

            TreeQueries tq = new TreeQueries(treeDB, fieldsColl);
            tq.groupByFriendlyName();

            System.out.println("Please enter a width and height: ");
            int width = scanner.nextInt();
            int height = scanner.nextInt();
            tq.friendlyNameBySection(width, height);

        } catch (Exception e) {
            System.out.println("ERROR");
            System.out.println(e);
        }

        scanner.close();
    }
}
